server:
  port: 3001
  servlet:
    context-path: /api/v1

spring:
  application:
    name: backend
  flyway:
    baseline-on-migrate: false
    enabled: true
    locations: classpath:db/migration
    schemas: ff
    default-schema: ff

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ff?currentSchema=ff
    username: postgres
    password: postgres

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
#  packages-to-scan: br.com.ff.controllers
  paths-to-match: /**

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
logging:
  level:
    root: INFO
#    br.com.ff: DEBUG